### PR TITLE
Project structure refactoring and more building options support

### PR DESCRIPTION
**Pull request by be5invis**
This PR will talk about refactoring the project structure and providing more building options like XCode project.

### CODE REVIEW

**Comment by be5invis** [comment]
@schriftgestalt Does the XCode files generated in this branch work?

**Comment by schriftgestalt** [comment]
the Xcode projects are generated but the header paths are not correct.

**Comment by be5invis** [comment]
@schriftgestalt How?
ps. you can try to change the "includedirs" to test whether it fixes.

**Comment by schriftgestalt** [comment]
I wrote that somewhere already. It needs to be: `../../dep/** ../../src/**`.

**Comment by be5invis** [comment]
@schriftgestalt Like the latest commit?
The project files looks like this now
```
USER_HEADER_SEARCH_PATHS = (
	../../dep,
	../../src,
	../../dep/extern,
	"../../dep/extern/emyg-dtoa",
	../../src/cli,
	../../src/font,
	../../src/fontops,
	../../src/support,
	../../src/tables,
	../../src/fontops/otl,
	../../src/tables/CFF,
	../../src/tables/otl,
);
```

**Comment by schriftgestalt** [comment]
I still produces the same setting.

**Comment by be5invis** [comment]
@schriftgestalt Could you please explain more precisely, which field of which file should be “`../../dep/** ../../src/**`”. I do not have a Mac so I cannot test on my own.

**Comment by be5invis** [comment]
@schriftgestalt I've modified the `premake5-xcode` itself to make it possible to build using XCode. Please check out the latest commit and tell me if you found anything wrong.
Screenshots from @darkfall.
image
image

**Comment by schriftgestalt** [comment]
It works now. 

One small issue. I would not set this keys:
CONFIGURATION_BUILD_DIR
CONFIGURATION_TEMP_DIR
OBJROOT
SYMROOT

They all should be empty. The build product will not be in the repository but in some Xcode/DerivedData folder. But that is what you expect.

**Comment by be5invis** [comment]
@schriftgestalt 
I set the output directory because all the binaries produced are placed under `bin/`. Linux and Clang/CL-MSVC settings use these dirs either.
The PR will be merged, and if you find any problem about building on Mac, please fire issues about it.

**Pull request merged**
