### PR TITLE
add Xcode project file

### PR DESCRIPTION
**Pull request by schriftgestalt**
I needed to move the 'extern' folder into source, otherwise Xcode picks up the wrong 'getopt' file.

### CODE REVIEW

**Comment by schriftgestalt** [comment]
The other build files are not updated, yet.

**Comment by be5invis** [comment]
Have you ever tried to use [Premake](https://premake.github.io/)?
I am using Premake to manage the building process, for both Linux and Windows.
I do not have a Mac so that there is no configuration for XCode.

ps. the `getopt.c` is for Windows MSVC only. On Linux or using MinGW it is simply ignored.

**Comment by schriftgestalt** [comment]
I did compile it as described in the Linux section. That worked fine. But debugging is so much easier in Xcode ...

**Comment by be5invis** [comment]
@schriftgestalt I think you can add some configurations in `premake.lua` to add a `xcode` action.

**Comment by be5invis** [comment]
@schriftgestalt I've add a `xcode4` action to `premake5.lua` in [this branch](https://github.com/caryll/otfcc/tree/xcode-project).
You can checkout whether it works (using the `premake5 xcode4` and check out the workspace files inside `build/xcode`).

**Comment by schriftgestalt** [comment]
I checked it. The configuration need this change:

ALWAYS_SEARCH_USER_PATHS = YES
USER_HEADER_SEARCH_PATHS = ../../dep/** ../../src/**

And for projects like this, it is a but annoying to have so many sub projects.

**Comment by be5invis** [comment]
@schriftgestalt 
Searching subdirectories in `dep` and `src` are needless, given that `dep/polyfill-msvc/getopt.h` is needless for Xcode.

**Comment by schriftgestalt** [comment]
Nur otherwise it does not finds the files in 'extern'. That was the reason to put the extern folder into src.

**Comment by schriftgestalt** [comment]
But for some reason your Xcode projects didn't complain about the wrong getopt. I have to check that tomorrow.

**Comment by be5invis** [comment]
@schriftgestalt
XCode does not support specifying multiple header search directory? That's bad.
I will open another PR to talk about project structure and more building backends.
Sorry for closing this PR, I will not include any IDE-specific files that can be generated from `premake5`.

**Comment by be5invis** [comment]
The discussions and latest code are moved to #19.

**Pull request closed without merging**
